///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Validaciones
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validar_PorgramaDePagos recording.
    /// </summary>
    [TestModule("fe8a943d-afb2-4b5f-bb5c-a644e2475e2f", ModuleType.Recording, 1)]
    public partial class Validar_PorgramaDePagos : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Validar_PorgramaDePagos instance = new Validar_PorgramaDePagos();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validar_PorgramaDePagos()
        {
            CantCuotas = "";
            Fila = "1";
            Ambiente = "suragwqa2.segurossura.com.ar";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validar_PorgramaDePagos Instance
        {
            get { return instance; }
        }

#region Variables

        string _CantCuotas;

        /// <summary>
        /// Gets or sets the value of variable CantCuotas.
        /// </summary>
        [TestVariable("0244a9e5-2c7a-4090-8635-3bdf5362b9eb")]
        public string CantCuotas
        {
            get { return _CantCuotas; }
            set { _CantCuotas = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Fila.
        /// </summary>
        [TestVariable("391c7eea-3d13-4690-8b39-7e4e466444e8")]
        public string Fila
        {
            get { return repo.Fila; }
            set { repo.Fila = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.Validacion_ProgramaPagos.txt_PlanDePagos_CantCuotas' and assigning the part of its value captured by '[0-9]+' to variable 'CantCuotas'.", repo.SURA.Validacion_ProgramaPagos.txt_PlanDePagos_CantCuotasInfo, new RecordItemIndex(0));
            CantCuotas = repo.SURA.Validacion_ProgramaPagos.txt_PlanDePagos_CantCuotas.Element.GetAttributeValueText("InnerText", new Regex("[0-9]+"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", CantCuotas, new RecordItemIndex(1));
            
            validarCantidadCuotas();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -500 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-500);
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.tabla_ProgramaPagos, false, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
