///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Validaciones
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validar_InformacionPoliza_AnulacionPorReemplazo recording.
    /// </summary>
    [TestModule("5df05c4d-0261-4802-af19-730bc346c754", ModuleType.Recording, 1)]
    public partial class Validar_InformacionPoliza_AnulacionPorReemplazo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Validar_InformacionPoliza_AnulacionPorReemplazo instance = new Validar_InformacionPoliza_AnulacionPorReemplazo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validar_InformacionPoliza_AnulacionPorReemplazo()
        {
            PolizaAnulada = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validar_InformacionPoliza_AnulacionPorReemplazo Instance
        {
            get { return instance; }
        }

#region Variables

        string _PolizaAnulada;

        /// <summary>
        /// Gets or sets the value of variable PolizaAnulada.
        /// </summary>
        [TestVariable("074b1a86-d68a-4d3e-9bc5-d1a54f04eaeb")]
        public string PolizaAnulada
        {
            get { return _PolizaAnulada; }
            set { _PolizaAnulada = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Validar que se indique en el origen el número de póliza
            Report.Log(ReportLevel.Info, "Section", "Validar que se indique en el origen el número de póliza", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_Origen'.", repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_OrigenInfo, new RecordItemIndex(1));
            Validate.Exists(repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_OrigenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_Origen' and assigning the part of its value captured by '[0-9]+' to variable 'PolizaAnulada'.", repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_OrigenInfo, new RecordItemIndex(2));
            PolizaAnulada = repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.txt_Origen.Element.GetAttributeValueText("InnerText", new Regex("[0-9]+"));
            Delay.Milliseconds(0);
            
            // La poliza anulada por reemplazo es:
            Report.Log(ReportLevel.Info, "Section", "La poliza anulada por reemplazo es:", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "User", PolizaAnulada, new RecordItemIndex(4));
            
            // Validar que no se pueda modificar la fecha de inicio de vigencia
            Report.Log(ReportLevel.Info, "Section", "Validar que no se pueda modificar la fecha de inicio de vigencia", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.validation_txt_Fecha_Inicio'.", repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.validation_txt_Fecha_InicioInfo, new RecordItemIndex(6));
            Validate.NotExists(repo.SURA_ContinueOnFail.Validacion_AnulacionPorReemplazo.validation_txt_Fecha_InicioInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
