///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Coberturas_NoEnlatado_Answer recording.
    /// </summary>
    [TestModule("3767acfb-e438-4103-9a60-a73c329f95ab", ModuleType.Recording, 1)]
    public partial class Coberturas_NoEnlatado_Answer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Coberturas_NoEnlatado_Answer instance = new Coberturas_NoEnlatado_Answer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Coberturas_NoEnlatado_Answer()
        {
            SumaAsegurada = "400000";
            NumPolizaEmitida = "";
            ValidateNroCuenta = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Coberturas_NoEnlatado_Answer Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumPolizaEmitida;

        /// <summary>
        /// Gets or sets the value of variable NumPolizaEmitida.
        /// </summary>
        [TestVariable("3d13f22b-664b-4945-a0bf-fe9a183cea47")]
        public string NumPolizaEmitida
        {
            get { return _NumPolizaEmitida; }
            set { _NumPolizaEmitida = value; }
        }

        string _ValidateNroCuenta;

        /// <summary>
        /// Gets or sets the value of variable ValidateNroCuenta.
        /// </summary>
        [TestVariable("93fda55f-a909-4c9a-8fe0-00e6c45bcfcc")]
        public string ValidateNroCuenta
        {
            get { return _ValidateNroCuenta; }
            set { _ValidateNroCuenta = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable SumaAsegurada.
        /// </summary>
        [TestVariable("0efb96cb-dd07-4a17-839f-f9a4b46fa708")]
        public string SumaAsegurada
        {
            get { return repo.SumaAsegurada; }
            set { repo.SumaAsegurada = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Btn_Incendio_Edificio_a_Prorrata' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Btn_Incendio_Edificio_a_ProrrataInfo, new RecordItemIndex(0));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Btn_Incendio_Edificio_a_Prorrata.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaInfo, new RecordItemIndex(1));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SumaAsegurada' with focus on 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada'.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaInfo, new RecordItemIndex(2));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada.PressKeys(SumaAsegurada);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.lbl_CoberturasIncendio' at Center.", repo.SURA.lbl_CoberturasIncendioInfo, new RecordItemIndex(3));
            //repo.SURA.lbl_CoberturasIncendio.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAsegurada'", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAseguradaInfo, new ActionTimeout(10000), new RecordItemIndex(4));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAseguradaInfo.WaitForNotExists(10000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Cotizar' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.CotizarInfo, new RecordItemIndex(6));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Cotizar.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Cotizar' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.CotizarInfo, new RecordItemIndex(7));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Cotizar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Cotizacion'", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.CotizacionInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.CotizacionInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(9));
            
            // Emitir Poliza
            Report.Log(ReportLevel.Info, "Section", "Emitir Poliza", new RecordItemIndex(10));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPoliza' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPolizaInfo, new RecordItemIndex(11));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPoliza.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            //Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_Aceptar' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_AceptarInfo, new RecordItemIndex(13));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_Aceptar.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratada'", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratadaInfo, new ActionTimeout(20000), new RecordItemIndex(14));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratadaInfo.WaitForExists(20000);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            //Delay.Duration(3000, false);
            
            //Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(16));
            
            // La poliza emitida es:
            //Report.Log(ReportLevel.Info, "Section", "La poliza emitida es:", new RecordItemIndex(17));
            
            //Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(18));
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.PC.Emision.Generales.InformacionDePoliza.Botones.NumeroDePolizaEmitida' and assigning the part of its value captured by '[0-9]+' to variable 'NumPolizaEmitida'.", repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.NumeroDePolizaEmitidaInfo, new RecordItemIndex(19));
            //NumPolizaEmitida = repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.NumeroDePolizaEmitida.Element.GetAttributeValueText("InnerText", new Regex("[0-9]+"));
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.validate_NroCuenta' and assigning its value to variable 'ValidateNroCuenta'.", repo.SURA.validate_NroCuentaInfo, new RecordItemIndex(20));
            //ValidateNroCuenta = repo.SURA.validate_NroCuenta.Element.GetAttributeValueText("InnerText");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", "El número de poliza emitida es:", new RecordItemIndex(21));
            
            //Report.Log(ReportLevel.Info, "User", NumPolizaEmitida, new RecordItemIndex(22));
            
            //Report.Log(ReportLevel.Info, "User", "Para la cuenta:", new RecordItemIndex(23));
            
            //Report.Log(ReportLevel.Info, "User", ValidateNroCuenta, new RecordItemIndex(24));
            
            //guardarNumPoliza();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
