///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sura.Emision
{
    public partial class Coberturas_HogarNoEnlatado
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SeleccionaCoberturaHogar()
        {
            // TODO: Replace the following line with your code implementation.
            //throw new NotImplementedException();
            
			
            if(!repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.ChkCoberturaInfo.Exists(5000)){
            	
            	Report.Info("No está tildado");
            	repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.OpcionCoberturaHogar.Click();
            	repo.SURA.lbl_CoberturasIncendio.Click();
            	Delay.Milliseconds(3000);
            	
            	//repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.Visible 
            	//Report.Info("Valor: " + repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.Value);
            	//if(repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.Value == null){
            		//Report.Info("Campo Suma Asegurada está visible");
            		//Report.Info("Valor de Suma Asegurada: " + SumaAseguradaCobHogar);
            		//repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.Click();
            		//Report.Info("Hizo Click");
            	
            	repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.PressKeys(SumaAseguradaCobHogar);
            	Report.Info("Escribió");
            	/*}else{
            		Report.Error("Campo Suma Asegurada NO está visible");
            	}*/
            
            }else{
            	
            	Report.Info("Está tildado");
            	Report.Info("Campo Suma Asegurada está visible");
            	Report.Info("Valor de Suma Asegurada: " + SumaAseguradaCobHogar);
            		//repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.Click();
            		//Report.Info("Hizo Click");
            	repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            	repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaCoberturaHogar.PressKeys(SumaAseguradaCobHogar);
            	Report.Info("Escribió");
            	
            }
        }
        

    }
}
