///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditarCuenta_CtaAnonima recording.
    /// </summary>
    [TestModule("3531d5c5-faa0-4ec8-b3ff-a7f1c9bafa9f", ModuleType.Recording, 1)]
    public partial class EditarCuenta_CtaAnonima : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static EditarCuenta_CtaAnonima instance = new EditarCuenta_CtaAnonima();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditarCuenta_CtaAnonima()
        {
            NroDocumento = "32145234";
            TextoSeleccionar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditarCuenta_CtaAnonima Instance
        {
            get { return instance; }
        }

#region Variables

        string _TextoSeleccionar;

        /// <summary>
        /// Gets or sets the value of variable TextoSeleccionar.
        /// </summary>
        [TestVariable("9082dd69-ec83-4e76-acc1-cfe822433dd9")]
        public string TextoSeleccionar
        {
            get { return _TextoSeleccionar; }
            set { _TextoSeleccionar = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroDocumento.
        /// </summary>
        [TestVariable("91eac8d1-e373-4259-9cd3-009bae16119c")]
        public string NroDocumento
        {
            get { return repo.NroDocumento; }
            set { repo.NroDocumento = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer' at Center.", repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswerInfo, new RecordItemIndex(0));
            repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer'.", repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswerInfo, new RecordItemIndex(1));
            repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroDocumento' with focus on 'SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer'.", repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswerInfo, new RecordItemIndex(2));
            repo.SURA.PC.Emision.PolizaAP.Personas.txt_nroDocumentoCtaAnonimaAnswer.PressKeys(NroDocumento);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Identificacion' at Center.", repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_IdentificacionInfo, new RecordItemIndex(3));
            repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Identificacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaAP.Personas.Copy_of_txt_nroDocumentoCtaAnonimaAnswer'", repo.SURA.PC.Emision.PolizaAP.Personas.Copy_of_txt_nroDocumentoCtaAnonimaAnswerInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.SURA.PC.Emision.PolizaAP.Personas.Copy_of_txt_nroDocumentoCtaAnonimaAnswerInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bttn_ValidarDocumento' at Center.", repo.SURA.bttn_ValidarDocumentoInfo, new RecordItemIndex(5));
            repo.SURA.bttn_ValidarDocumento.Click();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 10s to exist. Associated repository item: 'SURA_ContinueOnFail.lbl_VerifiedAddress_COF'", repo.SURA_ContinueOnFail.lbl_VerifiedAddress_COFInfo, new ActionTimeout(10000), new RecordItemIndex(6));
                repo.SURA_ContinueOnFail.lbl_VerifiedAddress_COFInfo.WaitForExists(10000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Get Value", "(Optional Action)\r\nGetting attribute 'InnerText' from item 'SURA_ContinueOnFail.Lnk_Seleccionar_COF' and assigning its value to variable 'TextoSeleccionar'.", repo.SURA_ContinueOnFail.Lnk_Seleccionar_COFInfo, new RecordItemIndex(7));
                TextoSeleccionar = repo.SURA_ContinueOnFail.Lnk_Seleccionar_COF.Element.GetAttributeValueText("InnerText");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.InformacionDePoliza.Arrow_Select_ProvinciaCtaAnonima' at Center.", repo.SURA.PC.Emision.PolizaMotor.InformacionDePoliza.Arrow_Select_ProvinciaCtaAnonimaInfo, new RecordItemIndex(8));
            //repo.SURA.PC.Emision.PolizaMotor.InformacionDePoliza.Arrow_Select_ProvinciaCtaAnonima.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.PolizaMotor.InformacionDePoliza.txt_ProvinciaCtaAnonima'", repo.SURA.PC.Emision.PolizaMotor.InformacionDePoliza.txt_ProvinciaCtaAnonimaInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            //repo.SURA.PC.Emision.PolizaMotor.InformacionDePoliza.txt_ProvinciaCtaAnonimaInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
