///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Loguear_InfoInspeccion recording.
    /// </summary>
    [TestModule("e95e9f23-700e-4f35-bffd-9e096406b9f7", ModuleType.Recording, 1)]
    public partial class Loguear_InfoInspeccion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Loguear_InfoInspeccion instance = new Loguear_InfoInspeccion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Loguear_InfoInspeccion()
        {
            NumEsquema = "";
            NombreEsquema = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Loguear_InfoInspeccion Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumEsquema;

        /// <summary>
        /// Gets or sets the value of variable NumEsquema.
        /// </summary>
        [TestVariable("3dcc018d-1f81-46d5-a5fd-0d3b9c37de76")]
        public string NumEsquema
        {
            get { return _NumEsquema; }
            set { _NumEsquema = value; }
        }

        string _NombreEsquema;

        /// <summary>
        /// Gets or sets the value of variable NombreEsquema.
        /// </summary>
        [TestVariable("97e58d79-1f9c-4061-86f7-af10a43bdc65")]
        public string NombreEsquema
        {
            get { return _NombreEsquema; }
            set { _NombreEsquema = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "El esquema validado en esta inspeccion es:", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", NumEsquema, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "User", NombreEsquema, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
