///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SeleccionCoberturaAdicional recording.
    /// </summary>
    [TestModule("01f9a0c1-879a-434d-b2a2-385559e481c8", ModuleType.Recording, 1)]
    public partial class SeleccionCoberturaAdicional : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static SeleccionCoberturaAdicional instance = new SeleccionCoberturaAdicional();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SeleccionCoberturaAdicional()
        {
            NombreCobertura = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SeleccionCoberturaAdicional Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NombreCobertura.
        /// </summary>
        [TestVariable("1ba66223-16a6-41d0-8b84-aeb7748fd49a")]
        public string NombreCobertura
        {
            get { return repo.NombreCobertura; }
            set { repo.NombreCobertura = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.Accesorios.OptionCobAdicional' at 5;5.", repo.SURA.PC.Emision.PolizaMotor.Accesorios.OptionCobAdicionalInfo, new RecordItemIndex(0));
            repo.SURA.PC.Emision.PolizaMotor.Accesorios.OptionCobAdicional.Click("5;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.PolizaMotor.Accesorios.TxtBoxControl'", repo.SURA.PC.Emision.PolizaMotor.Accesorios.TxtBoxControlInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SURA.PC.Emision.PolizaMotor.Accesorios.TxtBoxControlInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
