///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SeleccionaDireccion recording.
    /// </summary>
    [TestModule("b578dea9-0a16-49a5-97cf-ab2054d90ba8", ModuleType.Recording, 1)]
    public partial class SeleccionaDireccion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static SeleccionaDireccion instance = new SeleccionaDireccion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SeleccionaDireccion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SeleccionaDireccion Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.Lnk_Seleccionar' at Center.", repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.Lnk_SeleccionarInfo, new RecordItemIndex(0));
            repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.Lnk_Seleccionar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.lbl_DireccionVerificada'", repo.SURA.lbl_DireccionVerificadaInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SURA.lbl_DireccionVerificadaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Btn_ActualizarDireccion' at Center.", repo.SURA.Btn_ActualizarDireccionInfo, new RecordItemIndex(2));
            repo.SURA.Btn_ActualizarDireccion.Click();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 30s to exist. Associated repository item: 'SURA_ContinueOnFail.lbl_ExisteCtaAnonimaConMismoDNI_COF'", repo.SURA_ContinueOnFail.lbl_ExisteCtaAnonimaConMismoDNI_COFInfo, new ActionTimeout(30000), new RecordItemIndex(3));
                repo.SURA_ContinueOnFail.lbl_ExisteCtaAnonimaConMismoDNI_COFInfo.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'SURA.Btn_ActualizarDireccion' at Center.", repo.SURA.Btn_ActualizarDireccionInfo, new RecordItemIndex(4));
                repo.SURA.Btn_ActualizarDireccion.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.txt_Cotizacion1'", repo.SURA.txt_Cotizacion1Info, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SURA.txt_Cotizacion1Info.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
