///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SinAsistenciaMecanica recording.
    /// </summary>
    [TestModule("aea33a7c-b265-4357-910b-ea540d6569eb", ModuleType.Recording, 1)]
    public partial class SinAsistenciaMecanica : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static SinAsistenciaMecanica instance = new SinAsistenciaMecanica();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SinAsistenciaMecanica()
        {
            AsistenciaMecanica = "Sin Asistencia";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SinAsistenciaMecanica Instance
        {
            get { return instance; }
        }

#region Variables

        string _AsistenciaMecanica;

        /// <summary>
        /// Gets or sets the value of variable AsistenciaMecanica.
        /// </summary>
        [TestVariable("785c87e9-4520-4713-abba-483ccec9f5e9")]
        public string AsistenciaMecanica
        {
            get { return _AsistenciaMecanica; }
            set { _AsistenciaMecanica = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Txt_Validacion.txt_Coberturas' at 40;7.", repo.SURA.PC.Txt_Validacion.txt_CoberturasInfo, new RecordItemIndex(0));
            repo.SURA.PC.Txt_Validacion.txt_Coberturas.Click("40;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Proveedor' at Center.", repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_ProveedorInfo, new RecordItemIndex(1));
            repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Proveedor.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible' at Center.", repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisibleInfo, new RecordItemIndex(2));
            repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible'.", repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisibleInfo, new RecordItemIndex(3));
            repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AsistenciaMecanica' with focus on 'SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible'.", repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisibleInfo, new RecordItemIndex(4));
            repo.SURA.PC.Emision.PolizaMotor.txt_ProveedorAsistMecanicaVisible.PressKeys(AsistenciaMecanica);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Proveedor' at Center.", repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_ProveedorInfo, new RecordItemIndex(5));
            repo.SURA.PC.Emision.PolizaMotor.CoberturasAdicionales.lbl_Proveedor.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
