///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VehiculosFlota_Parte2 recording.
    /// </summary>
    [TestModule("e4d58108-8cec-4d52-8288-3a8b254d536e", ModuleType.Recording, 1)]
    public partial class VehiculosFlota_Parte2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static VehiculosFlota_Parte2 instance = new VehiculosFlota_Parte2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VehiculosFlota_Parte2()
        {
            NroTransaccion = "";
            NombreArchivo = "Solicitud_de_Póliza_0053204177_Personas_Aseguradas_20241017-1652.xlsx";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VehiculosFlota_Parte2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _NombreArchivo;

        /// <summary>
        /// Gets or sets the value of variable NombreArchivo.
        /// </summary>
        [TestVariable("969ad8e6-2199-48ef-8ce3-4fd75879e537")]
        public string NombreArchivo
        {
            get { return _NombreArchivo; }
            set { _NombreArchivo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable nomArchivoSinExt.
        /// </summary>
        [TestVariable("8d6c4cc6-2a76-41e9-9a55-7a82792a7faf")]
        public string nomArchivoSinExt
        {
            get { return repo.nomArchivoSinExt; }
            set { repo.nomArchivoSinExt = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroTransaccion.
        /// </summary>
        [TestVariable("2fa98842-caed-4d63-8ced-94871481d132")]
        public string NroTransaccion
        {
            get { return repo.NroTransaccion; }
            set { repo.NroTransaccion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Importar Archivo
            Report.Log(ReportLevel.Info, "Section", "Importar Archivo", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.Flota.bttn_Importar' at Center.", repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_ImportarInfo, new RecordItemIndex(1));
            repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_Importar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.txt_ImportarDeLaHojaDeCalculo'", repo.SURA.txt_ImportarDeLaHojaDeCalculoInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.SURA.txt_ImportarDeLaHojaDeCalculoInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Flota_Nomina.btn_ExaminarImport' at Center.", repo.SURA.PC.Emision.Flota_Nomina.btn_ExaminarImportInfo, new RecordItemIndex(3));
            repo.SURA.PC.Emision.Flota_Nomina.btn_ExaminarImport.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'VentanaEmergente_Examinar'", repo.VentanaEmergente_Examinar.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.VentanaEmergente_Examinar.SelfInfo.WaitForExists(30000);
            
            // Ventana Emergente
            Report.Log(ReportLevel.Info, "Section", "Ventana Emergente", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VentanaEmergente_Examinar.Escritorio' at Center.", repo.VentanaEmergente_Examinar.EscritorioInfo, new RecordItemIndex(6));
            repo.VentanaEmergente_Examinar.Escritorio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\TEMP\\'.", new RecordItemIndex(7));
            Keyboard.Press("C:\\TEMP\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(8));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VentanaEmergente_Examinar.BarraInferior' at Center.", repo.VentanaEmergente_Examinar.BarraInferiorInfo, new RecordItemIndex(9));
            repo.VentanaEmergente_Examinar.BarraInferior.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NombreArchivo'.", new RecordItemIndex(10));
            Keyboard.Press(NombreArchivo);
            Delay.Milliseconds(0);
            
            //ingresarNombreArchivo();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VentanaEmergente_Examinar.ButtonOpen' at Center.", repo.VentanaEmergente_Examinar.ButtonOpenInfo, new RecordItemIndex(12));
            repo.VentanaEmergente_Examinar.ButtonOpen.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            // Carga de Archivo Finalizada
            Report.Log(ReportLevel.Info, "Section", "Carga de Archivo Finalizada", new RecordItemIndex(14));
            
            quitaExt();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.PolizaMotor.Flota.bttn_Importar'", repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_ImportarInfo, new ActionTimeout(30000), new RecordItemIndex(16));
            repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_ImportarInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaMotor.Flota.bttn_Importar' at Center.", repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_ImportarInfo, new RecordItemIndex(17));
            repo.SURA.PC.Emision.PolizaMotor.Flota.bttn_Importar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Endosos2.PolicyChangeWizardLOBWizardStepGroupLi1.ResumenDeImportacion'", repo.SURA.PC.Endosos2.PolicyChangeWizardLOBWizardStepGroupLi1.ResumenDeImportacionInfo, new ActionTimeout(30000), new RecordItemIndex(18));
            repo.SURA.PC.Endosos2.PolicyChangeWizardLOBWizardStepGroupLi1.ResumenDeImportacionInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.bttn_Aceptar4' at Center.", repo.SURA_ContinueOnFail.bttn_Aceptar4Info, new RecordItemIndex(19));
            repo.SURA_ContinueOnFail.bttn_Aceptar4.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.Generales.InformacionDePoliza.lbl_NroDeVehiculo'", repo.SURA.PC.Emision.Generales.InformacionDePoliza.lbl_NroDeVehiculoInfo, new ActionTimeout(30000), new RecordItemIndex(20));
            repo.SURA.PC.Emision.Generales.InformacionDePoliza.lbl_NroDeVehiculoInfo.WaitForExists(30000);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.Flota_Nomina.Flota.lbl_ColoqueArchivos'", repo.SURA.PC.Emision.Flota_Nomina.Flota.lbl_ColoqueArchivosInfo, new ActionTimeout(30000), new RecordItemIndex(21));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.lbl_ColoqueArchivosInfo.WaitForExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumento' at Center.", repo.SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumentoInfo, new RecordItemIndex(22));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumento.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Flota_Nomina.Flota.item_TipoDocumento' at Center.", repo.SURA.PC.Emision.Flota_Nomina.Flota.item_TipoDocumentoInfo, new RecordItemIndex(23));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.item_TipoDocumento.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumentoLleno'", repo.SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumentoLlenoInfo, new ActionTimeout(30000), new RecordItemIndex(24));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.cbo_TipoDocumentoLlenoInfo.WaitForExists(30000);
            
            // Finaliza Importacion
            Report.Log(ReportLevel.Info, "Section", "Finaliza Importacion", new RecordItemIndex(25));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Flota_Nomina.Flota.btn_GuardarCerrar' at Center.", repo.SURA.PC.Emision.Flota_Nomina.Flota.btn_GuardarCerrarInfo, new RecordItemIndex(26));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.btn_GuardarCerrar.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_TituloCargaDocumentos'", repo.SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_TituloCargaDocumentosInfo, new ActionTimeout(30000), new RecordItemIndex(27));
            //repo.SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_TituloCargaDocumentosInfo.WaitForNotExists(30000);
            
            // Continua Proceso de Alta
            Report.Log(ReportLevel.Info, "Section", "Continua Proceso de Alta", new RecordItemIndex(28));
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            //Delay.Duration(1000, false);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'SURA_ContinueOnFail.btn_UltimaPagina' at Center.", repo.SURA_ContinueOnFail.btn_UltimaPaginaInfo, new RecordItemIndex(30));
                //repo.SURA_ContinueOnFail.btn_UltimaPagina.Click();
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(30)); }
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccion' at Center.", repo.SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccionInfo, new RecordItemIndex(31));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccion.MoveTo();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccion' at Center.", repo.SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccionInfo, new RecordItemIndex(32));
            //repo.SURA.PC.Emision.Flota_Nomina.Flota.lnk_NroTransaccion.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Txt_Validacion.txt_InformacionDePoliza'", repo.SURA.PC.Txt_Validacion.txt_InformacionDePolizaInfo, new ActionTimeout(30000), new RecordItemIndex(33));
            //repo.SURA.PC.Txt_Validacion.txt_InformacionDePolizaInfo.WaitForExists(30000);
            
            // Información de Póliza
            Report.Log(ReportLevel.Info, "Section", "Información de Póliza", new RecordItemIndex(34));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_Siguiente' at Center.", repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_SiguienteInfo, new RecordItemIndex(35));
            repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_Siguiente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.lbl_ComisionesDescuentos'", repo.SURA.lbl_ComisionesDescuentosInfo, new ActionTimeout(30000), new RecordItemIndex(36));
            repo.SURA.lbl_ComisionesDescuentosInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
