///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Menu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuSuperior_Poliza recording.
    /// </summary>
    [TestModule("8c3cc7b2-dae0-4f18-97b1-6b9eaf4b957a", ModuleType.Recording, 1)]
    public partial class MenuSuperior_Poliza : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static MenuSuperior_Poliza instance = new MenuSuperior_Poliza();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuSuperior_Poliza()
        {
            NumPoliza = "12420005062";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuSuperior_Poliza Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NumPoliza.
        /// </summary>
        [TestVariable("5b19c854-1a54-49cb-9047-6f69de5cc04a")]
        public string NumPoliza
        {
            get { return repo.NumPoliza; }
            set { repo.NumPoliza = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos.Generales.bttn_Poliza' at CenterRight.", repo.SURA.PC.Endosos.Generales.bttn_PolizaInfo, new RecordItemIndex(0));
            repo.SURA.PC.Endosos.Generales.bttn_Poliza.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NumPoliza' with focus on 'SURA.PC.Endosos.Generales.txtbox_NumPoliza'.", repo.SURA.PC.Endosos.Generales.txtbox_NumPolizaInfo, new RecordItemIndex(1));
            repo.SURA.PC.Endosos.Generales.txtbox_NumPoliza.PressKeys(NumPoliza);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SURA.PC.Endosos.Generales.txtbox_NumPoliza'.", repo.SURA.PC.Endosos.Generales.txtbox_NumPolizaInfo, new RecordItemIndex(2));
            repo.SURA.PC.Endosos.Generales.txtbox_NumPoliza.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_VerificarMS'", repo.SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_VerificarMSInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SURA.PC.Emision.PolizaMotor.SolicitudDePolizaNueva.lbl_VerificarMSInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
