///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Menu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuSupBuscaPolizaNroPoliza recording.
    /// </summary>
    [TestModule("8b3e91b0-9ee3-4807-bbac-d005248babe6", ModuleType.Recording, 1)]
    public partial class MenuSupBuscaPolizaNroPoliza : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static MenuSupBuscaPolizaNroPoliza instance = new MenuSupBuscaPolizaNroPoliza();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuSupBuscaPolizaNroPoliza()
        {
            NroTransaccion = "0010490216";
            NroPoliza = "04104012918";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuSupBuscaPolizaNroPoliza Instance
        {
            get { return instance; }
        }

#region Variables

        string _NroPoliza;

        /// <summary>
        /// Gets or sets the value of variable NroPoliza.
        /// </summary>
        [TestVariable("42428f7f-6975-4ad4-9ef7-76736c2aa29d")]
        public string NroPoliza
        {
            get { return _NroPoliza; }
            set { _NroPoliza = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroTransaccion.
        /// </summary>
        [TestVariable("27918312-f9f6-4869-a02d-22aad7214881")]
        public string NroTransaccion
        {
            get { return repo.NroTransaccion; }
            set { repo.NroTransaccion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bttn_Poliza' at CenterRight.", repo.SURA.bttn_PolizaInfo, new RecordItemIndex(0));
            repo.SURA.bttn_Poliza.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroPoliza' with focus on 'SURA.PC.Menu.Superior.txt_BusquedaPoliza'.", repo.SURA.PC.Menu.Superior.txt_BusquedaPolizaInfo, new RecordItemIndex(1));
            repo.SURA.PC.Menu.Superior.txt_BusquedaPoliza.PressKeys(NroPoliza);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SURA.PC.Menu.Superior.txt_BusquedaPoliza'.", repo.SURA.PC.Menu.Superior.txt_BusquedaPolizaInfo, new RecordItemIndex(2));
            repo.SURA.PC.Menu.Superior.txt_BusquedaPoliza.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.txt_InformacionDePoliza'", repo.SURA.txt_InformacionDePolizaInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SURA.txt_InformacionDePolizaInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
