///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Menu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuSuperior_PolizaBC recording.
    /// </summary>
    [TestModule("756e4f17-f3bf-40aa-9387-498ace36db34", ModuleType.Recording, 1)]
    public partial class MenuSuperior_PolizaBC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static MenuSuperior_PolizaBC instance = new MenuSuperior_PolizaBC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuSuperior_PolizaBC()
        {
            NroPoliza = "12112002274";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuSuperior_PolizaBC Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroPoliza.
        /// </summary>
        [TestVariable("4a75ea4b-f65f-496b-82a8-b8bc13f349ab")]
        public string NroPoliza
        {
            get { return repo.NroPoliza; }
            set { repo.NroPoliza = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.BC.bttn_PolizaBC' at CenterRight.", repo.SURA.BC.bttn_PolizaBCInfo, new RecordItemIndex(0));
            repo.SURA.BC.bttn_PolizaBC.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroPoliza' with focus on 'SURA.BC.input_BusquedaPolizaBC'.", repo.SURA.BC.input_BusquedaPolizaBCInfo, new RecordItemIndex(1));
            repo.SURA.BC.input_BusquedaPolizaBC.PressKeys(NroPoliza);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SURA.BC.input_BusquedaPolizaBC'.", repo.SURA.BC.input_BusquedaPolizaBCInfo, new RecordItemIndex(2));
            repo.SURA.BC.input_BusquedaPolizaBC.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.BC.txt_ResumenDePoliza'", repo.SURA.BC.txt_ResumenDePolizaInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SURA.BC.txt_ResumenDePolizaInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
