///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////
using Microsoft.Office.Interop.Excel;
using System.IO;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sura.ValidacionMarcaModelo
{
    public partial class ValidacionStatus
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void GrabaExcel()
        {
            // TODO: Replace the following line with your code implementation.
            //throw new NotImplementedException();
            String Resultado = String.Empty;
            var excelApp = new Microsoft.Office.Interop.Excel.Application();
           
			

            
            switch (Status){​​​​​​

                 case "0":

                     Report.Info("INFO","PASS");
                     Resultado = "PASS";
                     break;

                 case "1":

                     Report.Info("INFO","FAIL: Fallo la MARCA");
                     Resultado = "FAIL";
                     break;

                 case "2":

                     Report.Info("INFO","FAIL: Fallo el MODELO");
                     Resultado = "FAIL";
                     break;

                 case "3":

                     Report.Info("INFO","FAIL: Falla MARCA y MODELO");
                     Resultado = "FAIL";
                     break;

             }
            
            Report.Info("Info:",Resultado);
            
            //Tomo el valor del exe de la aplicacion ranorex
             string directory = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);

             //Combino el path de la aplicacion ranorex con el path dinamico que deseo agregar (en este caso subo 3 niveles)
             string path = System.IO.Path.GetFullPath(System.IO.Path.Combine(directory,@"../../../DataSource/"));
          
            excelApp.Workbooks.Open(path + "DataSource_Validacion_Polizas_Emitidas_Marcas_Modelo.xlsx");
            excelApp.Visible=false;
            //Selecciono el WorkSheet
			((Microsoft.Office.Interop.Excel.Worksheet)excelApp.ActiveWorkbook.Sheets["Hoja1"]).Select();
			
            
            
            int i = 1;

             //Mientras no haya una celda vacia...

             while (excelApp.Range["A"+i].Value != null)

             {​​​​

                 //Verificamos si el valor de la celda contiene el Nro de documento

                 if (excelApp.Range["A"+i].Value.ToString() == ID)

                 {​​​​

                     //Se ingresa el valor correspondiente

                     excelApp.Range["K"+i].Value = Resultado;

                     Report.Log(ReportLevel.Info,"ATENTO","Se agrego a la fila: " + i + " el valor: " + Resultado);

                     break;

                 }​​​​

                    i++;

             }
             
             //Elimino las Alertas
             excelApp.DisplayAlerts = false;

             //Grabo el archivo
             //excelApp.Save();
             excelApp.ActiveWorkbook.Save();
           
			//FileInfo excelFile = new FileInfo(path + "DataSource_Validacion_Polizas_Emitidas_Marcas_Modelo_1.xlsx");
			//excelApp.SaveAs(excelFile);
			//Workbook wb = excel.Workbooks.Add();


             //Cierro el Excel
             excelApp.Workbooks.Close();​​​​
            ​​​​​​
        }

    }
}
