///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.ValidacionMarcaModelo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidaMarcaModelo_Codigo recording.
    /// </summary>
    [TestModule("8cb5da30-e7c8-49f4-a58a-a86c7d6c264f", ModuleType.Recording, 1)]
    public partial class ValidaMarcaModelo_Codigo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static ValidaMarcaModelo_Codigo instance = new ValidaMarcaModelo_Codigo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidaMarcaModelo_Codigo()
        {
            Marca = "SIN MARCA";
            Modelo = "TRAILER ZUMUVA";
            ValidaMarca = "";
            ValidaModelo = "";
            Status = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidaMarcaModelo_Codigo Instance
        {
            get { return instance; }
        }

#region Variables

        string _ValidaMarca;

        /// <summary>
        /// Gets or sets the value of variable ValidaMarca.
        /// </summary>
        [TestVariable("101e34ce-812e-43fc-9ae1-3021b1afc184")]
        public string ValidaMarca
        {
            get { return _ValidaMarca; }
            set { _ValidaMarca = value; }
        }

        string _ValidaModelo;

        /// <summary>
        /// Gets or sets the value of variable ValidaModelo.
        /// </summary>
        [TestVariable("36e8e591-e55e-4102-b04c-946987def0f9")]
        public string ValidaModelo
        {
            get { return _ValidaModelo; }
            set { _ValidaModelo = value; }
        }

        string _Status;

        /// <summary>
        /// Gets or sets the value of variable Status.
        /// </summary>
        [TestVariable("63c50532-b0c6-4a11-902a-db2942b03f0e")]
        public string Status
        {
            get { return _Status; }
            set { _Status = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Marca.
        /// </summary>
        [TestVariable("f5419ceb-f99f-4274-a0e6-f65c291bc2a7")]
        public string Marca
        {
            get { return repo.Marca; }
            set { repo.Marca = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Modelo.
        /// </summary>
        [TestVariable("4e03eff3-0ade-4325-83dc-34fecdcb03c8")]
        public string Modelo
        {
            get { return repo.Modelo; }
            set { repo.Modelo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$Marca) on item 'SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Marca'.", repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_MarcaInfo, new RecordItemIndex(0));
                //Validate.AttributeEqual(repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_MarcaInfo, "InnerText", Marca, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$Modelo) on item 'SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Modelo'.", repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_ModeloInfo, new RecordItemIndex(1));
                //Validate.AttributeEqual(repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_ModeloInfo, "InnerText", Modelo, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Marca' and assigning its value to variable 'ValidaMarca'.", repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_MarcaInfo, new RecordItemIndex(2));
            ValidaMarca = repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Marca.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Modelo' and assigning its value to variable 'ValidaModelo'.", repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_ModeloInfo, new RecordItemIndex(3));
            ValidaModelo = repo.SURA.PC.Emision.PolizaMotor.ValidacionMarcaModelo.Copy_of_Modelo.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Validacion();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
