///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sura.Endosos
{
    public partial class EmitirEndoso
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void AprobacionBloqueo()
        {
            // TODO: Replace the following line with your code implementation.
            //throw new NotImplementedException();
            Report.Info("Info:","Esperando el Botón Detalle por 10s");
            if(repo.SURA_ContinueOnFail.btn_DetallesInfo.Exists(10000)){
            
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.btn_Detalles' at Center.", repo.SURA_ContinueOnFail.btn_DetallesInfo, new RecordItemIndex(4));
	            repo.SURA_ContinueOnFail.btn_Detalles.Click();
	            
	            Report.Info("Info:","Ciclo de Aprobación Especial");
	            while(repo.SURA_ContinueOnFail.btn_AprobacionEspecialInfo.Exists(5000)){
	            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.btn_AprobacionEspecial' at Center.", repo.SURA_ContinueOnFail.btn_AprobacionEspecialInfo, new RecordItemIndex(5));
	           		repo.SURA_ContinueOnFail.btn_AprobacionEspecial.Click();
	           		
	           		Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.bttn_AceptarCOF' at Center.", repo.SURA_ContinueOnFail.bttn_AceptarCOFInfo, new RecordItemIndex(6));
	            	repo.SURA_ContinueOnFail.bttn_AceptarCOF.Click();
	            
	            
	            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.bttn_Aceptar4' at Center.", repo.SURA_ContinueOnFail.bttn_Aceptar4Info, new RecordItemIndex(7));
	            	repo.SURA_ContinueOnFail.bttn_Aceptar4.Click();
	            }
	            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.btn_AprobacionEspecial' at Center.", repo.SURA_ContinueOnFail.btn_AprobacionEspecialInfo, new RecordItemIndex(5));
	            //repo.SURA_ContinueOnFail.btn_AprobacionEspecial.Click();
	            
	            
	            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.bttn_AceptarCOF' at Center.", repo.SURA_ContinueOnFail.bttn_AceptarCOFInfo, new RecordItemIndex(6));
	            //repo.SURA_ContinueOnFail.bttn_AceptarCOF.Click();
	            
	            
	            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_ContinueOnFail.bttn_Aceptar4' at Center.", repo.SURA_ContinueOnFail.bttn_Aceptar4Info, new RecordItemIndex(7));
	            //repo.SURA_ContinueOnFail.bttn_Aceptar4.Click();
	           
	            
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_EmitirPoliza' at Center.", repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_EmitirPolizaInfo, new RecordItemIndex(8));
	            repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_EmitirPoliza.Click();
	            
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos.Generales.bttn_EmitirEndoso' at Center.", repo.SURA.PC.Endosos.Generales.bttn_EmitirEndosoInfo, new RecordItemIndex(8));
	            repo.SURA.PC.Endosos.Generales.bttn_EmitirEndoso.Click();
	            
	            
	           Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_Aceptar' at Center.", repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_AceptarInfo, new RecordItemIndex(9));
	           repo.SURA.PC.Emision.Generales.InformacionDePoliza.Botones.bttn_Aceptar.Click();
            }
        }

    }
}
