///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Endosos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EndosoAP_Producto recording.
    /// </summary>
    [TestModule("24c848f1-8983-4461-9881-c06bb25010fe", ModuleType.Recording, 1)]
    public partial class EndosoAP_Producto : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static EndosoAP_Producto instance = new EndosoAP_Producto();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EndosoAP_Producto()
        {
            NuevaOferta = "AP Total";
            NuevaExtension = "Jornada Laboral";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EndosoAP_Producto Instance
        {
            get { return instance; }
        }

#region Variables

        string _NuevaOferta;

        /// <summary>
        /// Gets or sets the value of variable NuevaOferta.
        /// </summary>
        [TestVariable("fd23e81e-6339-41d4-a86d-8860c355c062")]
        public string NuevaOferta
        {
            get { return _NuevaOferta; }
            set { _NuevaOferta = value; }
        }

        string _NuevaExtension;

        /// <summary>
        /// Gets or sets the value of variable NuevaExtension.
        /// </summary>
        [TestVariable("6ad560b0-c693-401f-a4e7-a3d72db7a80b")]
        public string NuevaExtension
        {
            get { return _NuevaExtension; }
            set { _NuevaExtension = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "Información original", repo.SURA.Self, false, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos.AP.Coberturas.bttn_Producto' at 25;3.", repo.SURA.PC.Endosos.AP.Coberturas.bttn_ProductoInfo, new RecordItemIndex(1));
            repo.SURA.PC.Endosos.AP.Coberturas.bttn_Producto.Click("25;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Endosos.AP.Coberturas.txt_Producto'", repo.SURA.PC.Endosos.AP.Coberturas.txt_ProductoInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.SURA.PC.Endosos.AP.Coberturas.txt_ProductoInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertas'.", repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertasInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertas);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NuevaOferta' with focus on 'SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertas'.", repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertasInfo, new RecordItemIndex(4));
            repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_SeleccionDeOfertas.PressKeys(NuevaOferta);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos.AP.Coberturas.txt_Producto' at CenterRight.", repo.SURA.PC.Endosos.AP.Coberturas.txt_ProductoInfo, new RecordItemIndex(5));
            repo.SURA.PC.Endosos.AP.Coberturas.txt_Producto.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_SeleccionDeOfertas'", repo.SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_SeleccionDeOfertasInfo, new ActionTimeout(15000), new RecordItemIndex(6));
            repo.SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_SeleccionDeOfertasInfo.WaitForNotExists(15000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCobertura'.", repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCoberturaInfo, new RecordItemIndex(7));
            Keyboard.PrepareFocus(repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCobertura);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NuevaExtension' with focus on 'SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCobertura'.", repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCoberturaInfo, new RecordItemIndex(8));
            repo.SURA.PC.Emision.PolizaAP.Producto.txtbox_ExtensionDeCobertura.PressKeys(NuevaExtension);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos.AP.Coberturas.txt_Producto' at CenterRight.", repo.SURA.PC.Endosos.AP.Coberturas.txt_ProductoInfo, new RecordItemIndex(9));
            repo.SURA.PC.Endosos.AP.Coberturas.txt_Producto.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_AmbitoDeCobertura'", repo.SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_AmbitoDeCoberturaInfo, new ActionTimeout(15000), new RecordItemIndex(10));
            repo.SURA.PC.Emision.PolizaAP.Producto.Copy_of_txtbox_AmbitoDeCoberturaInfo.WaitForNotExists(15000);
            
            Report.Screenshot(ReportLevel.Info, "User", "Modificación producida por el endoso", repo.SURA.Self, false, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
