///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Endosos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Vehiculos_ModifCoberturas recording.
    /// </summary>
    [TestModule("1e016133-1517-479a-b8c1-8ef277e0376a", ModuleType.Recording, 1)]
    public partial class Vehiculos_ModifCoberturas : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Vehiculos_ModifCoberturas instance = new Vehiculos_ModifCoberturas();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Vehiculos_ModifCoberturas()
        {
            Producto = "A - Responsabilidad Civil Unicamente";
            ClausulaAjuste = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Vehiculos_ModifCoberturas Instance
        {
            get { return instance; }
        }

#region Variables

        string _ClausulaAjuste;

        /// <summary>
        /// Gets or sets the value of variable ClausulaAjuste.
        /// </summary>
        [TestVariable("692e2c7c-de83-4d01-bb57-5d85beabe43a")]
        public string ClausulaAjuste
        {
            get { return _ClausulaAjuste; }
            set { _ClausulaAjuste = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Producto.
        /// </summary>
        [TestVariable("e4e626a6-cd9f-4d9e-8e94-3988d5f13c0a")]
        public string Producto
        {
            get { return repo.Producto; }
            set { repo.Producto = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "Información original", repo.SURA.Self, false, new RecordItemIndex(0));
            
            // --------------------------------Producto
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Producto", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.ModifCoberturas.ProductosDisponibles' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.ProductosDisponiblesInfo, new RecordItemIndex(2));
            repo.SURA.PC.Endosos2.ModifCoberturas.ProductosDisponibles.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA'.", repo.SURA.SelfInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.SURA.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Producto' with focus on 'SURA'.", repo.SURA.SelfInfo, new RecordItemIndex(4));
            repo.SURA.Self.EnsureVisible();
            Keyboard.Press(Producto);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgo' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgoInfo, new RecordItemIndex(5));
            repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgo'", repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgoInfo, new ActionTimeout(10000), new RecordItemIndex(6));
            repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgoInfo.WaitForNotExists(10000);
            
            // --------------------------------Clausula de Ajuste
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Clausula de Ajuste", new RecordItemIndex(7));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.ModifCoberturas.XFormArrowTriggerXFormArrowTrigge11' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.XFormArrowTriggerXFormArrowTrigge11Info, new RecordItemIndex(8));
            //repo.SURA.PC.Endosos2.ModifCoberturas.XFormArrowTriggerXFormArrowTrigge11.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA'.", repo.SURA.SelfInfo, new RecordItemIndex(9));
            //Keyboard.PrepareFocus(repo.SURA.Self);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ClausulaAjuste' with focus on 'SURA'.", repo.SURA.SelfInfo, new RecordItemIndex(10));
            //repo.SURA.Self.EnsureVisible();
            //Keyboard.Press(ClausulaAjuste);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgo' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgoInfo, new RecordItemIndex(11));
            //repo.SURA.PC.Endosos2.ModifCoberturas.Copy_of_cbo_UbicacionRiesgo.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------Siguiente
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Siguiente", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "Modificación producida por el endoso", repo.SURA.Self, false, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.PC.Endosos2.ModifCoberturas.Siguiente1' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.Siguiente1Info, new RecordItemIndex(16));
            repo.SURA.PC.Endosos2.ModifCoberturas.Siguiente1.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.ModifCoberturas.Siguiente1' at Center.", repo.SURA.PC.Endosos2.ModifCoberturas.Siguiente1Info, new RecordItemIndex(17));
            repo.SURA.PC.Endosos2.ModifCoberturas.Siguiente1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 45s to exist. Associated repository item: 'SURA.PC.Endosos2.ModifCoberturas.title_Comisiones_Descuentos1'", repo.SURA.PC.Endosos2.ModifCoberturas.title_Comisiones_Descuentos1Info, new ActionTimeout(45000), new RecordItemIndex(18));
            repo.SURA.PC.Endosos2.ModifCoberturas.title_Comisiones_Descuentos1Info.WaitForExists(45000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
