///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura.Endosos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Vivienda_EndosoModifRiesgo recording.
    /// </summary>
    [TestModule("10d9f8eb-36fe-428f-af24-3d1ad0f44f48", ModuleType.Recording, 1)]
    public partial class Vivienda_EndosoModifRiesgo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sura.SuraRepository repository.
        /// </summary>
        public static global::Sura.SuraRepository repo = global::Sura.SuraRepository.Instance;

        static Vivienda_EndosoModifRiesgo instance = new Vivienda_EndosoModifRiesgo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Vivienda_EndosoModifRiesgo()
        {
            Provincia = "CAPITAL";
            Localidad = "CIUDAD AUTONOMA BUENOS AIRES";
            NvoPais = "Argentina";
            NvaPcia = "Capital";
            NvaCiudad = "CIUDAD";
            NvaCalle = "cabildo";
            NvoNro = "13";
            TipoVivienda = "Permanente";
            Producto = "Incendio";
            PlanPlanta = "Casa en PB o Depto hasta 1er piso";
            TipoConstruccion = "Construccion de Material y Techos Sólidos";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Vivienda_EndosoModifRiesgo Instance
        {
            get { return instance; }
        }

#region Variables

        string _NvoPais;

        /// <summary>
        /// Gets or sets the value of variable NvoPais.
        /// </summary>
        [TestVariable("7c9f8cb3-47b7-4430-8014-95d373026b18")]
        public string NvoPais
        {
            get { return _NvoPais; }
            set { _NvoPais = value; }
        }

        string _NvaPcia;

        /// <summary>
        /// Gets or sets the value of variable NvaPcia.
        /// </summary>
        [TestVariable("9c4a186c-2cf2-4310-b0bc-39d0eb82428f")]
        public string NvaPcia
        {
            get { return _NvaPcia; }
            set { _NvaPcia = value; }
        }

        string _NvaCiudad;

        /// <summary>
        /// Gets or sets the value of variable NvaCiudad.
        /// </summary>
        [TestVariable("acf3cc6b-2cff-4ca6-b609-1e2fdb53eba9")]
        public string NvaCiudad
        {
            get { return _NvaCiudad; }
            set { _NvaCiudad = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e249a1a2-b157-42ff-9826-60bc615aa12c")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Domicilio.
        /// </summary>
        [TestVariable("b4bf0cd3-712a-4c23-bb38-5301841e069e")]
        public string Domicilio
        {
            get { return repo.Domicilio; }
            set { repo.Domicilio = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Provincia.
        /// </summary>
        [TestVariable("048380ed-a1c5-4e14-a9d4-6ad634834ba4")]
        public string Provincia
        {
            get { return repo.PROVINCIA; }
            set { repo.PROVINCIA = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Localidad.
        /// </summary>
        [TestVariable("75c8f3f0-af55-485b-b6f8-8a21bb62bb51")]
        public string Localidad
        {
            get { return repo.LOCALIDAD; }
            set { repo.LOCALIDAD = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Producto.
        /// </summary>
        [TestVariable("cd3af81d-ca45-4845-8d57-6e132bc682fb")]
        public string Producto
        {
            get { return repo.Producto; }
            set { repo.Producto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PlanPlanta.
        /// </summary>
        [TestVariable("ed273a3e-ca2a-4aa0-94be-d4a78dd01eb6")]
        public string PlanPlanta
        {
            get { return repo.PlanPlanta; }
            set { repo.PlanPlanta = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoConstruccion.
        /// </summary>
        [TestVariable("056eb64e-3e6a-4e61-9c40-2256923ea8c5")]
        public string TipoConstruccion
        {
            get { return repo.TipoConstruccion; }
            set { repo.TipoConstruccion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NvaCalle.
        /// </summary>
        [TestVariable("d303b2f9-1f53-47c3-a611-5a2786d6357e")]
        public string NvaCalle
        {
            get { return repo.NvaCalle; }
            set { repo.NvaCalle = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NvoNro.
        /// </summary>
        [TestVariable("1278365b-a906-433d-8fec-f7889672ea2c")]
        public string NvoNro
        {
            get { return repo.NvoNro; }
            set { repo.NvoNro = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoVivienda.
        /// </summary>
        [TestVariable("3d310614-3757-4cc5-abe8-97559b095a0e")]
        public string TipoVivienda
        {
            get { return repo.TipoVivienda; }
            set { repo.TipoVivienda = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "Información original", repo.SURA.Self, false, new RecordItemIndex(0));
            
            // --------------------------------s
            Report.Log(ReportLevel.Info, "Section", "--------------------------------s", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.L_Vivienda_Modificacion' at Center.", repo.SURA.L_Vivienda_ModificacionInfo, new RecordItemIndex(2));
            repo.SURA.L_Vivienda_Modificacion.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------Cargo Provincia
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Provincia", new RecordItemIndex(3));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Provincia' at Center.", repo.SURA.ProvinciaInfo, new RecordItemIndex(4));
            //repo.SURA.Provincia.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.Provincia'.", repo.SURA.ProvinciaInfo, new RecordItemIndex(5));
            //Keyboard.PrepareFocus(repo.SURA.Provincia);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SURA.Provincia'.", repo.SURA.ProvinciaInfo, new RecordItemIndex(6));
            //repo.SURA.Provincia.EnsureVisible();
            //Keyboard.Press("{Delete}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Provincia' with focus on 'SURA.Provincia'.", repo.SURA.ProvinciaInfo, new RecordItemIndex(7));
            //repo.SURA.Provincia.EnsureVisible();
            //Keyboard.Press(Provincia);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            //Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_Provincia' at Center.", repo.SURA.cbo_ProvinciaInfo, new RecordItemIndex(9));
            //repo.SURA.cbo_Provincia.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------Cargo Localidad
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Localidad", new RecordItemIndex(10));
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            //Delay.Duration(2000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Localidad' at Center.", repo.SURA.LocalidadInfo, new RecordItemIndex(12));
            //repo.SURA.Localidad.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.Localidad'.", repo.SURA.LocalidadInfo, new RecordItemIndex(13));
            //Keyboard.PrepareFocus(repo.SURA.Localidad);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SURA.Localidad'.", repo.SURA.LocalidadInfo, new RecordItemIndex(14));
            //repo.SURA.Localidad.EnsureVisible();
            //Keyboard.Press("{Delete}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Localidad' with focus on 'SURA.Localidad'.", repo.SURA.LocalidadInfo, new RecordItemIndex(15));
            //repo.SURA.Localidad.EnsureVisible();
            //Keyboard.Press(Localidad);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_Localidad' at Center.", repo.SURA.cbo_LocalidadInfo, new RecordItemIndex(16));
            //repo.SURA.cbo_Localidad.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------Agrego Ubicacion Nueva
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Agrego Ubicacion Nueva", new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(18));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_UbicacionNueva' at Center.", repo.SURA.cbo_UbicacionNuevaInfo, new RecordItemIndex(19));
            repo.SURA.cbo_UbicacionNueva.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(20));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.EditarUbicacion'", repo.SURA.EditarUbicacionInfo, new ActionTimeout(30000), new RecordItemIndex(21));
            repo.SURA.EditarUbicacionInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Copy_of_EditarUbicacion' at Center.", repo.SURA.Copy_of_EditarUbicacionInfo, new RecordItemIndex(22));
            repo.SURA.Copy_of_EditarUbicacion.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------Cargo Datos Nueva Ubicacion
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Datos Nueva Ubicacion", new RecordItemIndex(23));
            
            // --------------------------------Nuevo pais
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Nuevo pais", new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_Pais' at Center.", repo.SURA.cbo_PaisInfo, new RecordItemIndex(25));
            repo.SURA.cbo_Pais.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.imp_Pais'.", repo.SURA.imp_PaisInfo, new RecordItemIndex(26));
            Keyboard.PrepareFocus(repo.SURA.imp_Pais);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NvoPais' with focus on 'SURA.imp_Pais'.", repo.SURA.imp_PaisInfo, new RecordItemIndex(27));
            repo.SURA.imp_Pais.EnsureVisible();
            Keyboard.Press(NvoPais);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.imp_Pais' at Center.", repo.SURA.imp_PaisInfo, new RecordItemIndex(28));
            repo.SURA.imp_Pais.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion' at Center.", repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacionInfo, new RecordItemIndex(29));
            repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------Nueva Pcia
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Nueva Pcia", new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(31));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to exist. Associated repository item: 'SURA.Copy_of_imp_NvaProvincia'", repo.SURA.Copy_of_imp_NvaProvinciaInfo, new ActionTimeout(15000), new RecordItemIndex(32));
            repo.SURA.Copy_of_imp_NvaProvinciaInfo.WaitForExists(15000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(33));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_NvaProvincia' at Center.", repo.SURA.cbo_NvaProvinciaInfo, new RecordItemIndex(34));
            repo.SURA.cbo_NvaProvincia.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1.5s.", new RecordItemIndex(35));
            Delay.Duration(1500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.imp_NvaProvincia_Endoso'.", repo.SURA.imp_NvaProvincia_EndosoInfo, new RecordItemIndex(36));
            Keyboard.PrepareFocus(repo.SURA.imp_NvaProvincia_Endoso);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NvaPcia' with focus on 'SURA.imp_NvaProvincia_Endoso'.", repo.SURA.imp_NvaProvincia_EndosoInfo, new RecordItemIndex(37));
            repo.SURA.imp_NvaProvincia_Endoso.EnsureVisible();
            Keyboard.Press(NvaPcia);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(38));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion' at Center.", repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacionInfo, new RecordItemIndex(39));
            repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_NvaLocalidad' at Center.", repo.SURA.cbo_NvaLocalidadInfo, new RecordItemIndex(40));
            //repo.SURA.cbo_NvaLocalidad.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------nueva localidad
            Report.Log(ReportLevel.Info, "Section", "--------------------------------nueva localidad", new RecordItemIndex(41));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(42));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_NvaLocalidad' at Center.", repo.SURA.cbo_NvaLocalidadInfo, new RecordItemIndex(43));
            repo.SURA.cbo_NvaLocalidad.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(44));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.Imp_NvaLocalidad_endoso'.", repo.SURA.Imp_NvaLocalidad_endosoInfo, new RecordItemIndex(45));
            Keyboard.PrepareFocus(repo.SURA.Imp_NvaLocalidad_endoso);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NvaCiudad' with focus on 'SURA.Imp_NvaLocalidad_endoso'.", repo.SURA.Imp_NvaLocalidad_endosoInfo, new RecordItemIndex(46));
            repo.SURA.Imp_NvaLocalidad_endoso.EnsureVisible();
            Keyboard.Press(NvaCiudad);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(47));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion' at Center.", repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacionInfo, new RecordItemIndex(48));
            repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Imp_NvaLocalidad_endoso' at Center.", repo.SURA.Imp_NvaLocalidad_endosoInfo, new RecordItemIndex(49));
            //repo.SURA.Imp_NvaLocalidad_endoso.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------nueva calle
            Report.Log(ReportLevel.Info, "Section", "--------------------------------nueva calle", new RecordItemIndex(50));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2.5s.", new RecordItemIndex(51));
            Delay.Duration(2500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.imp_NvaCalle' at Center.", repo.SURA.imp_NvaCalleInfo, new RecordItemIndex(52));
            repo.SURA.imp_NvaCalle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.imp_NvaCalle'.", repo.SURA.imp_NvaCalleInfo, new RecordItemIndex(53));
            Keyboard.PrepareFocus(repo.SURA.imp_NvaCalle);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(54));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NvaCalle' with focus on 'SURA.imp_NvaCalle'.", repo.SURA.imp_NvaCalleInfo, new RecordItemIndex(55));
            repo.SURA.imp_NvaCalle.PressKeys(NvaCalle);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(56));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion' at Center.", repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacionInfo, new RecordItemIndex(57));
            repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------nuevo numero
            Report.Log(ReportLevel.Info, "Section", "--------------------------------nuevo numero", new RecordItemIndex(58));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(59));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.imp_NvoNro' at Center.", repo.SURA.imp_NvoNroInfo, new RecordItemIndex(60));
            repo.SURA.imp_NvoNro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.imp_NvoNro'.", repo.SURA.imp_NvoNroInfo, new RecordItemIndex(61));
            Keyboard.PrepareFocus(repo.SURA.imp_NvoNro);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(62));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NvoNro' with focus on 'SURA.imp_NvoNro'.", repo.SURA.imp_NvoNroInfo, new RecordItemIndex(63));
            repo.SURA.imp_NvoNro.EnsureVisible();
            Keyboard.Press(NvoNro);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(64));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion' at Center.", repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacionInfo, new RecordItemIndex(65));
            repo.SURA.PC.Emision.PolizaHogar.Enlatado.txt_InformacionDeUbicacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(66));
            Delay.Duration(3000, false);
            
            // --------------------------------Validación Dirección
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Validación Dirección", new RecordItemIndex(67));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.btn_ValidarDireccion' at Center.", repo.SURA.btn_ValidarDireccionInfo, new RecordItemIndex(68));
            repo.SURA.btn_ValidarDireccion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(69));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to exist. Associated repository item: 'SURA.Copy_of_bttn_Aceptar2'", repo.SURA.Copy_of_bttn_Aceptar2Info, new ActionTimeout(15000), new RecordItemIndex(70));
            repo.SURA.Copy_of_bttn_Aceptar2Info.WaitForExists(15000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(71));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Copy_of_bttn_Aceptar2' at Center.", repo.SURA.Copy_of_bttn_Aceptar2Info, new RecordItemIndex(72));
            repo.SURA.Copy_of_bttn_Aceptar2.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bttn_Aceptar' at Center.", repo.SURA.bttn_AceptarInfo, new RecordItemIndex(73));
            //repo.SURA.bttn_Aceptar.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.title_Vivienda'", repo.SURA.title_ViviendaInfo, new ActionTimeout(30000), new RecordItemIndex(74));
            repo.SURA.title_ViviendaInfo.WaitForExists(30000);
            
            // --------------------------------Fin Datos Nueva Ubicacion
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Fin Datos Nueva Ubicacion", new RecordItemIndex(75));
            
            // --------------------------------Cargo Tipo de Vivienda
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Tipo de Vivienda", new RecordItemIndex(76));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.PC.Endosos2.Copy_of_cbo_TipoDeVivienda'", repo.SURA.PC.Endosos2.Copy_of_cbo_TipoDeViviendaInfo, new ActionTimeout(10000), new RecordItemIndex(77));
            repo.SURA.PC.Endosos2.Copy_of_cbo_TipoDeViviendaInfo.WaitForNotExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.cbo_TipoVivienda' at Center.", repo.SURA.cbo_TipoViviendaInfo, new RecordItemIndex(78));
            repo.SURA.cbo_TipoVivienda.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.cbo_TipoVivienda'.", repo.SURA.cbo_TipoViviendaInfo, new RecordItemIndex(79));
            Keyboard.PrepareFocus(repo.SURA.cbo_TipoVivienda);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoVivienda' with focus on 'SURA.cbo_TipoVivienda'.", repo.SURA.cbo_TipoViviendaInfo, new RecordItemIndex(80));
            repo.SURA.cbo_TipoVivienda.EnsureVisible();
            Keyboard.Press(TipoVivienda);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Copy_of_cbo_TipoVivienda' at Center.", repo.SURA.Copy_of_cbo_TipoViviendaInfo, new RecordItemIndex(81));
            repo.SURA.Copy_of_cbo_TipoVivienda.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(82));
            //Keyboard.Press("{Return}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(83));
            Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PantallaVivienda' at Center.", repo.SURA.PantallaViviendaInfo, new RecordItemIndex(84));
            //repo.SURA.PantallaVivienda.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------Cargo Producto
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Producto", new RecordItemIndex(85));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1.5s.", new RecordItemIndex(86));
            Delay.Duration(1500, false);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.PC.Endosos2.Copy_of_cbo_Producto'", repo.SURA.PC.Endosos2.Copy_of_cbo_ProductoInfo, new ActionTimeout(10000), new RecordItemIndex(87));
            //repo.SURA.PC.Endosos2.Copy_of_cbo_ProductoInfo.WaitForNotExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.Producto' at Center.", repo.SURA.PC.Endosos2.ProductoInfo, new RecordItemIndex(88));
            repo.SURA.PC.Endosos2.Producto.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.PC.Endosos2.Producto'.", repo.SURA.PC.Endosos2.ProductoInfo, new RecordItemIndex(89));
            Keyboard.PrepareFocus(repo.SURA.PC.Endosos2.Producto);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Producto' with focus on 'SURA.PC.Endosos2.Producto'.", repo.SURA.PC.Endosos2.ProductoInfo, new RecordItemIndex(90));
            repo.SURA.PC.Endosos2.Producto.EnsureVisible();
            Keyboard.Press(Producto);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.cbo_Producto' at Center.", repo.SURA.PC.Endosos2.cbo_ProductoInfo, new RecordItemIndex(91));
            repo.SURA.PC.Endosos2.cbo_Producto.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------Cargo Plan Planta
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Plan Planta", new RecordItemIndex(92));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(93));
            Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.PC.Endosos2.Copy_of_cbo_Plan_Planta'", repo.SURA.PC.Endosos2.Copy_of_cbo_Plan_PlantaInfo, new ActionTimeout(20000), new RecordItemIndex(94));
            //repo.SURA.PC.Endosos2.Copy_of_cbo_Plan_PlantaInfo.WaitForExists(20000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.Plan_Planta' at Center.", repo.SURA.PC.Endosos2.Plan_PlantaInfo, new RecordItemIndex(95));
            repo.SURA.PC.Endosos2.Plan_Planta.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(96));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.PC.Endosos2.Plan_Planta'.", repo.SURA.PC.Endosos2.Plan_PlantaInfo, new RecordItemIndex(97));
            Keyboard.PrepareFocus(repo.SURA.PC.Endosos2.Plan_Planta);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PlanPlanta' with focus on 'SURA.PC.Endosos2.Plan_Planta'.", repo.SURA.PC.Endosos2.Plan_PlantaInfo, new RecordItemIndex(98));
            repo.SURA.PC.Endosos2.Plan_Planta.EnsureVisible();
            Keyboard.Press(PlanPlanta);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(99));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.cbo_Plan_Planta' at Center.", repo.SURA.PC.Endosos2.cbo_Plan_PlantaInfo, new RecordItemIndex(100));
            repo.SURA.PC.Endosos2.cbo_Plan_Planta.Click();
            Delay.Milliseconds(0);
            
            // --------------------------------Cargo Tipo de Construccion
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Cargo Tipo de Construccion", new RecordItemIndex(101));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(102));
            Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to not exist. Associated repository item: 'SURA.PC.Endosos2.Copy_of_cbo_TipoDeConstruccion'", repo.SURA.PC.Endosos2.Copy_of_cbo_TipoDeConstruccionInfo, new ActionTimeout(15000), new RecordItemIndex(103));
            //repo.SURA.PC.Endosos2.Copy_of_cbo_TipoDeConstruccionInfo.WaitForNotExists(15000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.TipoDeConstruccion' at Center.", repo.SURA.PC.Endosos2.TipoDeConstruccionInfo, new RecordItemIndex(104));
            repo.SURA.PC.Endosos2.TipoDeConstruccion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SURA.PC.Endosos2.TipoDeConstruccion'.", repo.SURA.PC.Endosos2.TipoDeConstruccionInfo, new RecordItemIndex(105));
            Keyboard.PrepareFocus(repo.SURA.PC.Endosos2.TipoDeConstruccion);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoConstruccion' with focus on 'SURA.PC.Endosos2.TipoDeConstruccion'.", repo.SURA.PC.Endosos2.TipoDeConstruccionInfo, new RecordItemIndex(106));
            repo.SURA.PC.Endosos2.TipoDeConstruccion.EnsureVisible();
            Keyboard.Press(TipoConstruccion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.cbo_TipoDeConstruccion' at Center.", repo.SURA.PC.Endosos2.cbo_TipoDeConstruccionInfo, new RecordItemIndex(107));
            repo.SURA.PC.Endosos2.cbo_TipoDeConstruccion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(108));
            Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.bttn_Siguiente' at Center.", repo.SURA.PC.Endosos2.bttn_SiguienteInfo, new RecordItemIndex(109));
            //repo.SURA.PC.Endosos2.bttn_Siguiente.Click();
            //Delay.Milliseconds(0);
            
            // --------------------------------Siguiente
            Report.Log(ReportLevel.Info, "Section", "--------------------------------Siguiente", new RecordItemIndex(110));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Endosos2.Siguiente' at Center.", repo.SURA.PC.Endosos2.SiguienteInfo, new RecordItemIndex(111));
            repo.SURA.PC.Endosos2.Siguiente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 45s to exist. Associated repository item: 'SURA.PC.Endosos2.txt_Coberturas'", repo.SURA.PC.Endosos2.txt_CoberturasInfo, new ActionTimeout(45000), new RecordItemIndex(112));
            repo.SURA.PC.Endosos2.txt_CoberturasInfo.WaitForExists(45000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
